version: '3.8'

services:
  app:
    image: thinkthinking/wechat-mate:latest
    container_name: wechat_mate
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Asia/Shanghai
      - POSTGRES_HOST=postgres
      - DATABASE_URL=postgresql://chatbot:chatbot123@postgres:5432/chatbot
      - NODE_ENV=production

  postgres:
    image: postgres:17-alpine
    container_name: wechat_postgres
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot123
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Shanghai
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./install.postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: wechat_mate_postgres_data