version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: wechat_postgres_dev
    environment:
      POSTGRES_DB: chatbot
      POSTGRES_USER: chatbot
      POSTGRES_PASSWORD: chatbot123
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: Asia/Shanghai
      POSTGRES_INITDB_ARGS: --encoding=UTF8 --locale=C
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./install.postgres.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U chatbot"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data_dev:
    name: wechat_mate_postgres_data_dev
